name: Database Migration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'prisma/schema.prisma'
  workflow_dispatch:  # Allow manual triggering

jobs:
  migrate-staging:
    name: Migrate Staging Database
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations on staging
        run: |
          echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" > .env
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

      - name: Generate Prisma client
        run: npx prisma generate

  migrate-production:
    name: Migrate Production Database
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations on production
        run: |
          echo "DATABASE_URL=${{ secrets.PRODUCTION_DATABASE_URL }}" > .env
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - name: Generate Prisma client
        run: npx prisma generate
